// ──────────────────────────────────────────────
// Golfer Profile Data for SEO Pages
// ──────────────────────────────────────────────
// Static data for top PGA Tour golfers.
// Stats are representative of 2024-2025 season performance.
// ──────────────────────────────────────────────

export interface GolferProfile {
  name: string;
  slug: string;
  country: string;
  age: number;
  worldRanking: number;
  avgDfsPoints: number;
  winRate: number;     // % of tournaments won (career PGA Tour)
  cutRate: number;     // % made cut rate
  strokesGained: {
    offTheTee: number;
    approach: number;
    aroundTheGreen: number;
    putting: number;
    total: number;
  };
  recentResults: { tournament: string; finish: string }[];
  bio: string;
  dfsStrategyTips: string[];
  bestCourseFits: string[];   // course slugs from COURSE_PROFILES
  worstCourseFits: string[];  // course slugs from COURSE_PROFILES
}

export const GOLFER_PROFILES: Record<string, GolferProfile> = {
  'scottie-scheffler': {
    name: 'Scottie Scheffler',
    slug: 'scottie-scheffler',
    country: 'USA',
    age: 28,
    worldRanking: 1,
    avgDfsPoints: 82.4,
    winRate: 14.2,
    cutRate: 92.1,
    strokesGained: { offTheTee: 0.88, approach: 1.52, aroundTheGreen: 0.31, putting: 0.19, total: 2.90 },
    recentResults: [
      { tournament: 'THE PLAYERS Championship', finish: '1st' },
      { tournament: 'Arnold Palmer Invitational', finish: 'T3' },
      { tournament: 'WM Phoenix Open', finish: '2nd' },
      { tournament: 'The Masters', finish: '1st' },
      { tournament: 'PGA Championship', finish: 'T2' },
    ],
    bio: 'Scottie Scheffler has established himself as the dominant force in professional golf, holding the world number one ranking since 2022. A former University of Texas standout, Scheffler turned pro in 2018 and quickly ascended the PGA Tour ranks. His game is built on elite iron play and ball-striking precision — he leads the tour in strokes gained approach and tee-to-green. His two Masters victories and multiple signature event wins make him the most consistent high-floor, high-ceiling option in golf DFS. Scheffler rarely misses cuts, giving DFS players confidence that he will deliver four rounds of scoring. His ownership tends to be high, making him a better cash game play than GPP play in most weeks.',
    dfsStrategyTips: [
      'Scheffler is the safest cash game play in golf DFS — his 92%+ cut rate means you almost always get four rounds of scoring.',
      'In GPPs, Scheffler\'s high ownership (often 25-35%) limits his leverage value. Consider fading him in large-field tournaments where you need differentiation.',
      'His best DFS weeks come at ball-striker courses where approach play is weighted heavily — TPC Sawgrass, Augusta, and Bay Hill are prime spots.',
      'On DraftKings, Scheffler\'s consistency earns bogey-free round bonuses regularly, adding 3-6 bonus points per tournament.',
    ],
    bestCourseFits: ['augusta-national', 'tpc-sawgrass', 'bay-hill'],
    worstCourseFits: ['tpc-scottsdale', 'pinehurst-no2'],
  },
  'rory-mcilroy': {
    name: 'Rory McIlroy',
    slug: 'rory-mcilroy',
    country: 'Northern Ireland',
    age: 35,
    worldRanking: 3,
    avgDfsPoints: 76.8,
    winRate: 10.8,
    cutRate: 88.5,
    strokesGained: { offTheTee: 1.15, approach: 0.82, aroundTheGreen: -0.12, putting: 0.22, total: 2.07 },
    recentResults: [
      { tournament: 'Dubai Desert Classic', finish: '1st' },
      { tournament: 'Wells Fargo Championship', finish: 'T5' },
      { tournament: 'THE PLAYERS Championship', finish: 'T8' },
      { tournament: 'U.S. Open', finish: 'T2' },
      { tournament: 'RBC Canadian Open', finish: '1st' },
    ],
    bio: 'Rory McIlroy is a four-time major champion and one of the most talented ball-strikers in golf history. The Northern Irishman has been a consistent force on the PGA Tour since turning professional in 2007. McIlroy\'s game is defined by his elite driving — he consistently ranks near the top of the tour in driving distance and strokes gained off the tee. His approach play is strong but his short game around the green has historically been his weakness. When McIlroy is putting well, he is nearly unbeatable, as evidenced by his dominant major championship victories at the 2011 U.S. Open and 2012 PGA Championship. In DFS, McIlroy profiles as a high-ceiling play who excels at long, demanding courses where his power off the tee provides a clear advantage.',
    dfsStrategyTips: [
      'McIlroy is at his best on long, demanding courses where driving distance matters. Target him at Torrey Pines, Valhalla, and Augusta.',
      'His around-the-green weakness means he underperforms at courses with tricky greenside complexes like Pinehurst No. 2.',
      'McIlroy\'s ownership tends to be moderate (15-25%), making him a viable GPP pivot when the field is focused on other chalk plays.',
      'On FanDuel, McIlroy\'s occasional blow-up holes (double bogeys) are more costly. He\'s a slightly better DraftKings play due to DK\'s more forgiving bogey scoring.',
    ],
    bestCourseFits: ['torrey-pines-south', 'augusta-national', 'valhalla'],
    worstCourseFits: ['pinehurst-no2', 'pebble-beach'],
  },
  'xander-schauffele': {
    name: 'Xander Schauffele',
    slug: 'xander-schauffele',
    country: 'USA',
    age: 31,
    worldRanking: 2,
    avgDfsPoints: 78.2,
    winRate: 8.5,
    cutRate: 90.3,
    strokesGained: { offTheTee: 0.65, approach: 1.10, aroundTheGreen: 0.28, putting: 0.38, total: 2.41 },
    recentResults: [
      { tournament: 'PGA Championship', finish: '1st' },
      { tournament: 'The Open Championship', finish: '1st' },
      { tournament: 'THE PLAYERS Championship', finish: 'T6' },
      { tournament: 'Genesis Invitational', finish: 'T4' },
      { tournament: 'Arnold Palmer Invitational', finish: 'T10' },
    ],
    bio: 'Xander Schauffele broke through in 2024 with back-to-back major championship victories at the PGA Championship and The Open Championship, finally silencing critics who questioned whether he could win the biggest events. The San Diego native is one of the most well-rounded players on tour — he has no glaring weaknesses and ranks in the top 20 in nearly every strokes gained category. Schauffele\'s even-keeled temperament and consistent ball-striking make him an ideal DFS commodity. His approach play and putting have improved significantly, and he now profiles as a legitimate number one pick on any given week. Schauffele\'s versatility means he fits well at almost any course on the PGA Tour schedule.',
    dfsStrategyTips: [
      'Schauffele is one of the most versatile plays in DFS — he has no bad course fits and consistently delivers above-average results.',
      'His well-rounded strokes gained profile makes him a strong play at balanced courses like TPC Sawgrass and Bay Hill.',
      'Schauffele\'s high cut rate (90%+) and consistent scoring make him an elite cash game option alongside Scheffler.',
      'In GPPs, look for weeks when Schauffele\'s ownership dips below 15% — his ceiling is high enough to win any tournament.',
    ],
    bestCourseFits: ['tpc-sawgrass', 'bay-hill', 'tpc-scottsdale'],
    worstCourseFits: ['torrey-pines-south'],
  },
  'collin-morikawa': {
    name: 'Collin Morikawa',
    slug: 'collin-morikawa',
    country: 'USA',
    age: 28,
    worldRanking: 4,
    avgDfsPoints: 73.5,
    winRate: 7.2,
    cutRate: 89.1,
    strokesGained: { offTheTee: 0.35, approach: 1.45, aroundTheGreen: -0.05, putting: -0.10, total: 1.65 },
    recentResults: [
      { tournament: 'Zozo Championship', finish: '1st' },
      { tournament: 'THE PLAYERS Championship', finish: 'T12' },
      { tournament: 'Arnold Palmer Invitational', finish: 'T7' },
      { tournament: 'Masters Tournament', finish: 'T5' },
      { tournament: 'The Open Championship', finish: 'T3' },
    ],
    bio: 'Collin Morikawa is widely regarded as the best iron player in professional golf. The Cal-Berkeley graduate turned pro in 2019 and immediately made an impact, winning the PGA Championship in his first attempt as a professional in 2020. Morikawa\'s approach play is historically elite — he consistently ranks first or second on tour in strokes gained approach the green. His precision with mid-to-long irons is unmatched, allowing him to attack pins and create birdie opportunities that other golfers simply cannot. The trade-off is that Morikawa\'s putting and short game can be inconsistent, which creates variance in his DFS outcomes. When the flat stick cooperates, Morikawa is a tournament winner. When it doesn\'t, he can finish in the T20-T40 range despite elite ball-striking.',
    dfsStrategyTips: [
      'Morikawa is the prototypical approach-play specialist. He\'s at his best when SG: Approach is the most important stat for the week.',
      'Target him at TPC Sawgrass and Pebble Beach where precision iron play trumps driving distance.',
      'His putting inconsistency creates boom-or-bust DFS outcomes — this makes him a better GPP play than cash game play in most weeks.',
      'On weeks when Morikawa\'s price is depressed due to a recent missed cut, he\'s a strong buy-low GPP target.',
    ],
    bestCourseFits: ['tpc-sawgrass', 'pebble-beach', 'bay-hill'],
    worstCourseFits: ['torrey-pines-south', 'valhalla'],
  },
  'jon-rahm': {
    name: 'Jon Rahm',
    slug: 'jon-rahm',
    country: 'Spain',
    age: 30,
    worldRanking: 7,
    avgDfsPoints: 71.2,
    winRate: 9.5,
    cutRate: 86.8,
    strokesGained: { offTheTee: 0.92, approach: 1.05, aroundTheGreen: 0.18, putting: 0.15, total: 2.30 },
    recentResults: [
      { tournament: 'The Masters', finish: 'T6' },
      { tournament: 'LIV Golf Miami', finish: '2nd' },
      { tournament: 'U.S. Open', finish: 'T12' },
      { tournament: 'The Open Championship', finish: 'T9' },
      { tournament: 'PGA Championship', finish: 'T15' },
    ],
    bio: 'Jon Rahm is one of the most talented golfers of his generation, combining raw power with exceptional touch around the greens. The Spaniard won the 2021 U.S. Open and the 2023 Masters before departing for LIV Golf in late 2023. While his PGA Tour appearances have become limited, Rahm remains a force in major championships where he continues to compete. His game features elite driving and strong approach play, making him dangerous at longer courses. Rahm\'s fiery temperament can be both an asset and liability — he feeds off emotion and momentum, which creates high variance in his tournament outcomes. For DFS purposes, Rahm is primarily relevant in major championship weeks when he tees it up on the PGA Tour.',
    dfsStrategyTips: [
      'Rahm is now primarily a majors-only DFS play. Target him at the Masters, U.S. Open, Open Championship, and PGA Championship.',
      'His power-and-precision profile makes him elite at Augusta National and other long, demanding major venues.',
      'Rahm\'s ownership in majors tends to be moderate since he plays limited PGA Tour events, creating GPP value.',
      'Be cautious pricing him on DraftKings — he sometimes lacks the PGA Tour form indicators that predict major performance.',
    ],
    bestCourseFits: ['augusta-national', 'torrey-pines-south', 'valhalla'],
    worstCourseFits: ['tpc-scottsdale', 'pebble-beach'],
  },
  'ludvig-aberg': {
    name: 'Ludvig Aberg',
    slug: 'ludvig-aberg',
    country: 'Sweden',
    age: 25,
    worldRanking: 5,
    avgDfsPoints: 75.1,
    winRate: 6.0,
    cutRate: 87.5,
    strokesGained: { offTheTee: 0.95, approach: 1.20, aroundTheGreen: 0.10, putting: 0.05, total: 2.30 },
    recentResults: [
      { tournament: 'RSM Classic', finish: '1st' },
      { tournament: 'THE PLAYERS Championship', finish: 'T4' },
      { tournament: 'Masters Tournament', finish: '2nd' },
      { tournament: 'Arnold Palmer Invitational', finish: 'T8' },
      { tournament: 'WM Phoenix Open', finish: 'T6' },
    ],
    bio: 'Ludvig Aberg burst onto the PGA Tour scene with a maturity and ball-striking ability that belied his young age. The Swedish sensation turned professional in 2023 after a historic amateur career at Texas Tech and immediately made an impact, finishing runner-up at the 2024 Masters in just his second major championship appearance. Aberg\'s game is built on extraordinary length off the tee combined with precision iron play — a rare combination that makes him dangerous at virtually any venue. His strokes gained tee-to-green numbers are among the best on tour. While his putting and short game are still developing, the rest of his game is so elite that he consistently contends. In DFS, Aberg profiles as a high-ceiling play with slight floor risk due to his youth and occasional inconsistency on and around the greens.',
    dfsStrategyTips: [
      'Aberg\'s elite tee-to-green numbers make him one of the best ceiling plays in DFS. He can win any tournament he enters.',
      'Target Aberg at courses that reward length and iron play — Augusta, Torrey Pines, and Valhalla are ideal fits.',
      'His ownership has risen significantly since his Masters run. Look for weeks when ownership dips below 15% for GPP leverage.',
      'Aberg is slightly better on DraftKings than FanDuel because DK\'s forgiving bogey scoring protects against his occasional short game lapses.',
    ],
    bestCourseFits: ['augusta-national', 'torrey-pines-south', 'valhalla'],
    worstCourseFits: ['pinehurst-no2', 'pebble-beach'],
  },
  'wyndham-clark': {
    name: 'Wyndham Clark',
    slug: 'wyndham-clark',
    country: 'USA',
    age: 31,
    worldRanking: 6,
    avgDfsPoints: 70.8,
    winRate: 5.5,
    cutRate: 83.2,
    strokesGained: { offTheTee: 0.82, approach: 0.65, aroundTheGreen: 0.20, putting: 0.35, total: 2.02 },
    recentResults: [
      { tournament: 'U.S. Open', finish: '1st' },
      { tournament: 'Wells Fargo Championship', finish: '1st' },
      { tournament: 'AT&T Pebble Beach Pro-Am', finish: 'T3' },
      { tournament: 'THE PLAYERS Championship', finish: 'T15' },
      { tournament: 'Arnold Palmer Invitational', finish: 'T22' },
    ],
    bio: 'Wyndham Clark\'s breakout 2023 U.S. Open victory at Los Angeles Country Club announced his arrival as a legitimate top-tier talent on the PGA Tour. The University of Oregon product combines above-average length off the tee with solid putting, a profile that plays well at a variety of courses. Clark\'s game took a significant leap when his putting improved, allowing his ball-striking to translate into consistently strong finishes. His confidence has grown alongside his results, and he now enters most tournaments as a legitimate contender. In DFS, Clark offers a nice blend of upside and value — he\'s often priced below the true elite tier but has the talent to compete with anyone.',
    dfsStrategyTips: [
      'Clark offers value pricing relative to his talent level. He\'s frequently $1,000-$2,000 cheaper than comparably skilled golfers.',
      'His putting prowess makes him especially dangerous at courses where SG: Putting is heavily weighted, like TPC Scottsdale.',
      'Clark\'s moderate cut rate (83%) means he carries more floor risk than Scheffler or Schauffele — size your exposure accordingly in cash games.',
      'In GPPs, Clark is an excellent mid-tier target who can deliver a top-5 finish at lower ownership than the household names.',
    ],
    bestCourseFits: ['tpc-scottsdale', 'pebble-beach', 'bay-hill'],
    worstCourseFits: ['torrey-pines-south', 'valhalla'],
  },
  'viktor-hovland': {
    name: 'Viktor Hovland',
    slug: 'viktor-hovland',
    country: 'Norway',
    age: 27,
    worldRanking: 12,
    avgDfsPoints: 68.5,
    winRate: 6.8,
    cutRate: 85.0,
    strokesGained: { offTheTee: 0.55, approach: 0.92, aroundTheGreen: -0.45, putting: 0.30, total: 1.32 },
    recentResults: [
      { tournament: 'FedEx St. Jude Championship', finish: '1st' },
      { tournament: 'Tour Championship', finish: '1st' },
      { tournament: 'THE PLAYERS Championship', finish: 'T25' },
      { tournament: 'Memorial Tournament', finish: 'T18' },
      { tournament: 'WM Phoenix Open', finish: 'T12' },
    ],
    bio: 'Viktor Hovland is a supremely talented ball-striker from Norway who has won multiple PGA Tour events and became one of the youngest players to reach the top five in the world rankings. Hovland\'s game is characterized by excellent approach play and solid driving, but his short game around the green has been a persistent weakness throughout his career. When Hovland\'s chipping and pitching cooperate, as they did during his dominant 2023 FedExCup playoffs run, he is capable of winning any tournament on tour. However, his short game struggles can lead to frustrating weeks where strong ball-striking is undermined by poor up-and-downs. This volatility makes Hovland a fascinating DFS asset — he offers significant upside but with a floor that can crater when the short game goes sideways.',
    dfsStrategyTips: [
      'Hovland\'s short game weakness makes him a volatile DFS play. He\'s better suited for GPPs than cash games in most weeks.',
      'Avoid Hovland at courses with penalizing greenside complexes — Pinehurst No. 2 and similar courses amplify his weakness.',
      'He excels at courses where approach play and driving matter more than short game, such as Augusta National and TPC Sawgrass.',
      'Monitor Hovland\'s recent short game stats week-to-week. When his chipping numbers improve temporarily, his ceiling is enormous.',
    ],
    bestCourseFits: ['augusta-national', 'tpc-sawgrass', 'valhalla'],
    worstCourseFits: ['pinehurst-no2', 'pebble-beach'],
  },
  'patrick-cantlay': {
    name: 'Patrick Cantlay',
    slug: 'patrick-cantlay',
    country: 'USA',
    age: 32,
    worldRanking: 9,
    avgDfsPoints: 69.8,
    winRate: 6.0,
    cutRate: 89.8,
    strokesGained: { offTheTee: 0.22, approach: 0.85, aroundTheGreen: 0.40, putting: 0.48, total: 1.95 },
    recentResults: [
      { tournament: 'BMW Championship', finish: '1st' },
      { tournament: 'THE PLAYERS Championship', finish: 'T9' },
      { tournament: 'Arnold Palmer Invitational', finish: 'T6' },
      { tournament: 'Genesis Invitational', finish: 'T11' },
      { tournament: 'Masters Tournament', finish: 'T18' },
    ],
    bio: 'Patrick Cantlay is one of the most consistent and cerebral players on the PGA Tour. The UCLA product set the NCAA record for lowest scoring average and has translated that precision to the professional level. Cantlay\'s game is built on exceptional putting, elite short game touch, and precise approach play — he doesn\'t overpower courses with distance but instead dissects them with strategic placement and scoring prowess. His methodical approach to the game has earned him the nickname "Patty Ice" and multiple PGA Tour victories including the 2021 FedExCup championship. Cantlay\'s high cut rate and consistent scoring make him one of the most reliable DFS options available, though his lack of driving distance limits his ceiling at certain courses.',
    dfsStrategyTips: [
      'Cantlay is one of the safest DFS plays on tour with a near-90% cut rate. He\'s an ideal cash game anchor.',
      'His putting and short game excellence make him perfect for courses like TPC Scottsdale and Pebble Beach where touch matters.',
      'Avoid Cantlay at bomber-friendly courses like Torrey Pines South and Valhalla where his shorter driving distance is a liability.',
      'On FanDuel, Cantlay\'s bogey-avoidance profile is especially valuable given FD\'s harsher bogey penalties.',
    ],
    bestCourseFits: ['tpc-scottsdale', 'pebble-beach', 'tpc-sawgrass'],
    worstCourseFits: ['torrey-pines-south', 'valhalla'],
  },
  'sahith-theegala': {
    name: 'Sahith Theegala',
    slug: 'sahith-theegala',
    country: 'USA',
    age: 27,
    worldRanking: 8,
    avgDfsPoints: 72.1,
    winRate: 4.0,
    cutRate: 86.5,
    strokesGained: { offTheTee: 0.68, approach: 0.72, aroundTheGreen: 0.25, putting: 0.42, total: 2.07 },
    recentResults: [
      { tournament: 'Procore Championship', finish: '1st' },
      { tournament: 'THE PLAYERS Championship', finish: 'T5' },
      { tournament: 'WM Phoenix Open', finish: 'T3' },
      { tournament: 'Arnold Palmer Invitational', finish: 'T9' },
      { tournament: 'Masters Tournament', finish: 'T8' },
    ],
    bio: 'Sahith Theegala has emerged as one of the PGA Tour\'s most exciting young talents, combining aggressive play with a well-rounded skill set. The Pepperdine University standout turned professional in 2020 and quickly built a reputation for his fearless approach and ability to go low. Theegala\'s balanced strokes gained profile — with positive numbers in every category — makes him one of the most versatile players on tour. He contends regularly and has proven he can compete at the highest level against the best fields. His aggressive style creates both birdie opportunities and occasional blow-up holes, giving him a high-variance DFS profile that GPP players find especially attractive.',
    dfsStrategyTips: [
      'Theegala\'s well-rounded game makes him playable at almost any course on tour. He has no glaring weaknesses to exploit.',
      'His aggressive playing style creates high variance — expect either a top-10 or a T40+ finish in most weeks.',
      'Theegala is often underpriced relative to his skill level, making him an excellent value play in the mid-salary tier.',
      'Target him in GPPs when his ownership is projected below 12% — his ceiling is top-5 caliber at most venues.',
    ],
    bestCourseFits: ['tpc-scottsdale', 'bay-hill', 'tpc-sawgrass'],
    worstCourseFits: ['pinehurst-no2'],
  },
  'hideki-matsuyama': {
    name: 'Hideki Matsuyama',
    slug: 'hideki-matsuyama',
    country: 'Japan',
    age: 32,
    worldRanking: 10,
    avgDfsPoints: 71.5,
    winRate: 6.2,
    cutRate: 85.8,
    strokesGained: { offTheTee: 0.48, approach: 1.30, aroundTheGreen: 0.15, putting: -0.15, total: 1.78 },
    recentResults: [
      { tournament: 'Genesis Invitational', finish: '1st' },
      { tournament: 'Masters Tournament', finish: 'T4' },
      { tournament: 'THE PLAYERS Championship', finish: 'T11' },
      { tournament: 'Sony Open', finish: '1st' },
      { tournament: 'PGA Championship', finish: 'T8' },
    ],
    bio: 'Hideki Matsuyama made history in 2021 by becoming the first Japanese golfer to win the Masters Tournament, cementing his legacy as one of Asia\'s greatest golfers. Matsuyama\'s game is defined by his world-class iron play — he consistently ranks among the tour leaders in strokes gained approach, with a ball-flight and trajectory control that rivals anyone in the game. His driving has improved in recent years, giving him more scoring opportunities on longer courses. The main question mark in Matsuyama\'s game has always been his putting, which can be streaky. When the putter is hot, Matsuyama can dominate any field. His recent resurgence has reminded the golf world that he remains one of the most talented players in the game, regardless of the putting variance.',
    dfsStrategyTips: [
      'Matsuyama is one of the best approach players on tour. Target him at courses where SG: Approach is heavily weighted.',
      'His putting inconsistency creates GPP-friendly variance. When the putter is on, he can win; when it\'s off, he finishes 30th+.',
      'Matsuyama tends to play well at Augusta National and other courses he has extensive experience at — course history matters with him.',
      'He\'s often underowned in non-major tournaments, creating excellent GPP leverage opportunities.',
    ],
    bestCourseFits: ['tpc-sawgrass', 'augusta-national', 'pebble-beach'],
    worstCourseFits: ['tpc-scottsdale', 'pinehurst-no2'],
  },
  'tommy-fleetwood': {
    name: 'Tommy Fleetwood',
    slug: 'tommy-fleetwood',
    country: 'England',
    age: 34,
    worldRanking: 11,
    avgDfsPoints: 67.2,
    winRate: 3.8,
    cutRate: 87.2,
    strokesGained: { offTheTee: 0.55, approach: 0.78, aroundTheGreen: 0.22, putting: 0.18, total: 1.73 },
    recentResults: [
      { tournament: 'Dubai Desert Classic', finish: 'T2' },
      { tournament: 'THE PLAYERS Championship', finish: 'T14' },
      { tournament: 'Arnold Palmer Invitational', finish: 'T5' },
      { tournament: 'The Open Championship', finish: 'T6' },
      { tournament: 'U.S. Open', finish: 'T4' },
    ],
    bio: 'Tommy Fleetwood is one of the most well-rounded and likable players in professional golf. The Englishman has been a consistent performer on both the PGA and European Tours, with a game that features solid driving, accurate iron play, and dependable putting. Fleetwood\'s versatility allows him to compete at a wide variety of courses, and he has multiple runner-up finishes in major championships. His ability to perform in varying conditions — from the links of The Open Championship to the parkland courses of the PGA Tour — speaks to his adaptability. In DFS, Fleetwood profiles as a reliable mid-tier option who rarely craters but also has the ceiling to contend for wins when all facets of his game are clicking.',
    dfsStrategyTips: [
      'Fleetwood is a consistent mid-tier DFS play with a high floor. His 87%+ cut rate makes him reliable in cash games.',
      'He excels in poor weather conditions and links-style venues, making him a strong play at courses exposed to wind.',
      'Fleetwood\'s ownership tends to be moderate, giving him decent GPP leverage in most weeks.',
      'His balanced profile makes him a solid play at TPC Sawgrass, Bay Hill, and other courses that reward all-around play.',
    ],
    bestCourseFits: ['bay-hill', 'tpc-sawgrass', 'pebble-beach'],
    worstCourseFits: ['torrey-pines-south', 'valhalla'],
  },
  'shane-lowry': {
    name: 'Shane Lowry',
    slug: 'shane-lowry',
    country: 'Ireland',
    age: 37,
    worldRanking: 13,
    avgDfsPoints: 65.8,
    winRate: 4.2,
    cutRate: 84.5,
    strokesGained: { offTheTee: 0.15, approach: 0.62, aroundTheGreen: 0.55, putting: 0.32, total: 1.64 },
    recentResults: [
      { tournament: 'Cognizant Classic', finish: '1st' },
      { tournament: 'THE PLAYERS Championship', finish: 'T18' },
      { tournament: 'The Open Championship', finish: 'T5' },
      { tournament: 'RBC Heritage', finish: 'T8' },
      { tournament: 'Arnold Palmer Invitational', finish: 'T15' },
    ],
    bio: 'Shane Lowry endeared himself to the golf world with his emotional 2019 Open Championship victory at Royal Portrush in his native Ireland. The Offaly native has built a reputation as one of the best short game artists on tour, with elite touch around the greens and reliable putting that compensates for his relatively modest length off the tee. Lowry thrives in tough conditions where scrambling ability and mental toughness matter more than raw power. His experience and craftiness make him especially dangerous at courses with challenging greenside complexes. In DFS, Lowry is a classic short-game specialist play who offers strong value when priced appropriately.',
    dfsStrategyTips: [
      'Lowry\'s elite short game makes him a premium play at Pinehurst No. 2 and other courses with difficult greenside areas.',
      'Avoid him at long, bomber-friendly courses like Torrey Pines South where his lack of distance is a significant disadvantage.',
      'Lowry tends to be underowned in most weeks, making him an excellent GPP value play in the mid-to-low salary tier.',
      'He performs best in tough scoring conditions where the field struggles — look for him at courses with high difficulty ratings.',
    ],
    bestCourseFits: ['pinehurst-no2', 'pebble-beach', 'tpc-scottsdale'],
    worstCourseFits: ['torrey-pines-south', 'valhalla', 'augusta-national'],
  },
  'brooks-koepka': {
    name: 'Brooks Koepka',
    slug: 'brooks-koepka',
    country: 'USA',
    age: 35,
    worldRanking: 15,
    avgDfsPoints: 64.2,
    winRate: 8.0,
    cutRate: 78.5,
    strokesGained: { offTheTee: 0.88, approach: 0.72, aroundTheGreen: 0.05, putting: 0.10, total: 1.75 },
    recentResults: [
      { tournament: 'PGA Championship', finish: '1st' },
      { tournament: 'LIV Golf Jeddah', finish: 'T3' },
      { tournament: 'Masters Tournament', finish: 'T10' },
      { tournament: 'U.S. Open', finish: 'T22' },
      { tournament: 'The Open Championship', finish: 'T18' },
    ],
    bio: 'Brooks Koepka is a five-time major champion who brings an intimidating physical presence and unwavering confidence to every tournament he enters. The Florida native has proven himself on the biggest stages, with victories at the U.S. Open (2017, 2018), PGA Championship (2018, 2019, 2023), and multiple close calls at The Masters. Koepka\'s game is built on raw power off the tee and strong approach play, making him dangerous at the longest and most demanding courses in golf. His move to LIV Golf has limited his PGA Tour appearances to major championships, but he continues to perform at elite levels when the stakes are highest. In DFS, Koepka is a major-championship specialist who demands serious consideration when the game\'s biggest events arrive.',
    dfsStrategyTips: [
      'Like Rahm, Koepka is primarily a majors-only DFS play. His track record in majors is among the best in modern golf.',
      'Target Koepka at the PGA Championship and U.S. Open, where his power and major championship experience provide a clear edge.',
      'His ownership in majors can be surprisingly moderate due to his limited recent PGA Tour form data, creating GPP leverage.',
      'Koepka\'s all-or-nothing approach makes him a pure GPP play — he either contends or finishes in the 20s-30s.',
    ],
    bestCourseFits: ['valhalla', 'torrey-pines-south', 'augusta-national'],
    worstCourseFits: ['pebble-beach', 'tpc-scottsdale'],
  },
  'justin-thomas': {
    name: 'Justin Thomas',
    slug: 'justin-thomas',
    country: 'USA',
    age: 31,
    worldRanking: 14,
    avgDfsPoints: 66.5,
    winRate: 7.5,
    cutRate: 82.0,
    strokesGained: { offTheTee: 0.62, approach: 0.95, aroundTheGreen: 0.08, putting: 0.05, total: 1.70 },
    recentResults: [
      { tournament: 'Valspar Championship', finish: 'T4' },
      { tournament: 'THE PLAYERS Championship', finish: 'T20' },
      { tournament: 'PGA Championship', finish: 'T12' },
      { tournament: 'Memorial Tournament', finish: 'T9' },
      { tournament: 'Arnold Palmer Invitational', finish: 'T28' },
    ],
    bio: 'Justin Thomas is a two-time major champion and former world number one whose talent is undeniable. The Kentucky native burst onto the PGA Tour in 2015 and quickly established himself as one of the game\'s most prolific winners, with 15 PGA Tour victories by age 30. Thomas\'s game features elite approach play, solid driving, and the ability to go extremely low when hot — he holds the PGA Tour record for lowest 72-hole score in relation to par (253 at the 2017 Sony Open). While his form has been inconsistent in recent seasons, Thomas still possesses the shot-making ability to win any tournament. His inconsistency has led to lower DFS pricing, which can create significant value when he puts four strong rounds together.',
    dfsStrategyTips: [
      'Thomas is a classic buy-low candidate in DFS. When his price drops after a poor stretch, his ceiling remains top-5 caliber.',
      'His elite approach play makes him a strong fit at TPC Sawgrass, Augusta, and other precision-demanding courses.',
      'Thomas\'s inconsistency (82% cut rate) means he\'s better suited for GPPs than cash games in his current form.',
      'Watch for weeks when Thomas is priced in the $7,500-$8,500 range on DraftKings — that\'s where the value sweet spot lives.',
    ],
    bestCourseFits: ['tpc-sawgrass', 'augusta-national', 'bay-hill'],
    worstCourseFits: ['pinehurst-no2', 'torrey-pines-south'],
  },
  'tony-finau': {
    name: 'Tony Finau',
    slug: 'tony-finau',
    country: 'USA',
    age: 35,
    worldRanking: 16,
    avgDfsPoints: 68.2,
    winRate: 5.0,
    cutRate: 86.0,
    strokesGained: { offTheTee: 0.78, approach: 0.65, aroundTheGreen: 0.12, putting: 0.18, total: 1.73 },
    recentResults: [
      { tournament: 'Houston Open', finish: '1st' },
      { tournament: 'THE PLAYERS Championship', finish: 'T16' },
      { tournament: 'Arnold Palmer Invitational', finish: 'T12' },
      { tournament: 'Rocket Mortgage Classic', finish: '1st' },
      { tournament: 'Masters Tournament', finish: 'T15' },
    ],
    bio: 'Tony Finau is one of the most physically gifted athletes on the PGA Tour, possessing rare length off the tee combined with soft hands around the greens. The Utah native has been a consistent top-20 player on tour for nearly a decade, with his win rate increasing significantly in recent years. Finau\'s combination of driving distance, solid approach play, and improved putting has made him a regular contender at most venues. His calm demeanor and ability to perform under pressure make him especially dangerous in high-stakes tournament situations. In DFS, Finau offers a reliable blend of upside and floor protection, with his length providing scoring opportunities at courses that reward distance.',
    dfsStrategyTips: [
      'Finau is one of the most consistent mid-tier options in DFS. His balanced profile and 86% cut rate provide reliable floor production.',
      'His length off the tee makes him ideal for courses like Torrey Pines South and Valhalla where driving distance correlates with success.',
      'Finau\'s ownership tends to be in the 8-15% range, offering moderate GPP leverage without the risk of very low-owned dart throws.',
      'He\'s an excellent FanDuel play because his consistency aligns with FD\'s scoring system that punishes bogeys more heavily.',
    ],
    bestCourseFits: ['torrey-pines-south', 'valhalla', 'bay-hill'],
    worstCourseFits: ['pebble-beach', 'pinehurst-no2'],
  },
  'max-homa': {
    name: 'Max Homa',
    slug: 'max-homa',
    country: 'USA',
    age: 34,
    worldRanking: 18,
    avgDfsPoints: 65.5,
    winRate: 5.5,
    cutRate: 84.0,
    strokesGained: { offTheTee: 0.52, approach: 0.68, aroundTheGreen: 0.28, putting: 0.15, total: 1.63 },
    recentResults: [
      { tournament: 'Genesis Invitational', finish: 'T3' },
      { tournament: 'Wells Fargo Championship', finish: '1st' },
      { tournament: 'THE PLAYERS Championship', finish: 'T22' },
      { tournament: 'Arnold Palmer Invitational', finish: 'T14' },
      { tournament: 'Farmers Insurance Open', finish: 'T9' },
    ],
    bio: 'Max Homa has become one of the most popular and relatable players on the PGA Tour, combining five tour victories with an engaging social media presence that has endeared him to fans worldwide. The Cal-Berkeley product struggled early in his professional career before finding his form and becoming a regular contender. Homa\'s game is well-rounded with particular strengths in approach play and around the green, where his touch and creativity shine. He\'s one of the best scramblers on tour, which gives him a reliable floor even on weeks when his ball-striking isn\'t at its best. Homa thrives at courses he knows well, with particularly strong records at the Genesis Invitational (Riviera) and Wells Fargo Championship (Quail Hollow).',
    dfsStrategyTips: [
      'Homa is a strong course-history play. Check his past results at each venue — he tends to either love or hate specific courses.',
      'His scrambling ability provides a nice floor, making him a reasonable cash game option when priced in the mid-tier.',
      'Homa is at his best in the $7,500-$9,000 DraftKings salary range, where his upside provides strong value.',
      'Target him at courses with difficult greenside areas where his short game can separate him from the field.',
    ],
    bestCourseFits: ['bay-hill', 'tpc-sawgrass', 'pinehurst-no2'],
    worstCourseFits: ['torrey-pines-south', 'valhalla'],
  },
  'sungjae-im': {
    name: 'Sungjae Im',
    slug: 'sungjae-im',
    country: 'South Korea',
    age: 26,
    worldRanking: 17,
    avgDfsPoints: 67.8,
    winRate: 3.5,
    cutRate: 91.2,
    strokesGained: { offTheTee: 0.32, approach: 0.70, aroundTheGreen: 0.22, putting: 0.35, total: 1.59 },
    recentResults: [
      { tournament: 'Shriners Children\'s Open', finish: '1st' },
      { tournament: 'THE PLAYERS Championship', finish: 'T7' },
      { tournament: 'Arnold Palmer Invitational', finish: 'T4' },
      { tournament: 'Wyndham Championship', finish: 'T2' },
      { tournament: 'Masters Tournament', finish: 'T12' },
    ],
    bio: 'Sungjae Im is one of the most durable and consistent players on the PGA Tour, known for his iron-man schedule and remarkable cut-making ability. The South Korean native has one of the highest cut rates on tour, consistently playing four rounds week after week. Im\'s game is built on precision — he\'s not the longest off the tee but makes up for it with accurate iron play, solid putting, and excellent course management. His work ethic is legendary, and he plays more tournaments than virtually any other top player on tour. This volume of play gives DFS players a large sample size to evaluate his form and tendencies. Im profiles as one of the safest DFS plays available, with a consistently high floor even when his ceiling is moderate.',
    dfsStrategyTips: [
      'Im has one of the highest cut rates on tour (91%+), making him the ultimate cash game safety blanket.',
      'His lack of driving distance limits his ceiling at courses like Torrey Pines South and Augusta National.',
      'Im excels at shorter, precision-oriented courses like TPC Scottsdale and Pebble Beach.',
      'In GPPs, Im is better used as a floor play that allows you to take bigger swings with the rest of your lineup.',
    ],
    bestCourseFits: ['tpc-scottsdale', 'pebble-beach', 'tpc-sawgrass'],
    worstCourseFits: ['torrey-pines-south', 'valhalla', 'augusta-national'],
  },
  'cameron-young': {
    name: 'Cameron Young',
    slug: 'cameron-young',
    country: 'USA',
    age: 27,
    worldRanking: 20,
    avgDfsPoints: 66.2,
    winRate: 2.5,
    cutRate: 80.5,
    strokesGained: { offTheTee: 1.05, approach: 0.48, aroundTheGreen: 0.02, putting: -0.15, total: 1.40 },
    recentResults: [
      { tournament: 'THE PLAYERS Championship', finish: 'T3' },
      { tournament: 'RBC Heritage', finish: 'T6' },
      { tournament: 'Arnold Palmer Invitational', finish: 'T18' },
      { tournament: 'The Open Championship', finish: '2nd' },
      { tournament: 'Rocket Mortgage Classic', finish: 'T4' },
    ],
    bio: 'Cameron Young is one of the longest hitters on the PGA Tour and has accumulated an impressive collection of near-misses and runner-up finishes. The Wake Forest product generates elite clubhead speed, averaging over 310 yards off the tee, which gives him scoring opportunities that most players simply don\'t have. Young\'s approach play has improved steadily since his rookie season, though his putting remains the barrier between his current status and the winner\'s circle. He has finished second at both The Open Championship and the PGA Championship, demonstrating that his game is major-championship caliber. For DFS purposes, Young is a fascinating high-ceiling, moderate-floor option whose length off the tee creates birdie opportunities at courses where distance matters.',
    dfsStrategyTips: [
      'Young is one of the best ceiling plays in the mid-tier salary range. His driving distance creates birdie opportunities others can\'t access.',
      'Target him at long, bomber-friendly courses like Torrey Pines South and Valhalla where his driving is maximally valuable.',
      'His putting weakness creates significant variance — he can finish 5th or 50th depending on the week.',
      'Young is a pure GPP play. Avoid him in cash games where his lower cut rate and putting inconsistency create too much floor risk.',
    ],
    bestCourseFits: ['torrey-pines-south', 'valhalla', 'augusta-national'],
    worstCourseFits: ['pebble-beach', 'tpc-scottsdale'],
  },
  'matt-fitzpatrick': {
    name: 'Matt Fitzpatrick',
    slug: 'matt-fitzpatrick',
    country: 'England',
    age: 30,
    worldRanking: 19,
    avgDfsPoints: 64.8,
    winRate: 4.5,
    cutRate: 86.5,
    strokesGained: { offTheTee: -0.10, approach: 1.05, aroundTheGreen: 0.30, putting: 0.20, total: 1.45 },
    recentResults: [
      { tournament: 'RBC Heritage', finish: '1st' },
      { tournament: 'THE PLAYERS Championship', finish: 'T17' },
      { tournament: 'Masters Tournament', finish: 'T14' },
      { tournament: 'U.S. Open', finish: 'T8' },
      { tournament: 'Arnold Palmer Invitational', finish: 'T20' },
    ],
    bio: 'Matt Fitzpatrick is a U.S. Open champion and one of the most precise ball-strikers on tour despite being one of the shorter hitters in the elite tier. The Sheffield, England native won the 2022 U.S. Open at Brookline, proving that precision and course management can overcome a lack of raw power. Fitzpatrick\'s game revolves around elite approach play and strong short game — he consistently ranks among the tour leaders in strokes gained approach and around the green. His driving distance remains a limitation, but he has worked to add yardage in recent seasons. Fitzpatrick excels at courses that reward accuracy over distance, making him a specialist play in DFS rather than a universal option.',
    dfsStrategyTips: [
      'Fitzpatrick is the ideal play at precision-oriented courses where driving distance matters least.',
      'Target him at Pebble Beach, TPC Sawgrass, and Pinehurst No. 2 where his approach play and short game are maximally valuable.',
      'Avoid him at long, open courses like Torrey Pines South and Valhalla where his short driving distance becomes a liability.',
      'Fitzpatrick\'s ownership tends to be moderate, providing decent GPP leverage at his best courses.',
    ],
    bestCourseFits: ['pebble-beach', 'pinehurst-no2', 'tpc-sawgrass'],
    worstCourseFits: ['torrey-pines-south', 'valhalla', 'augusta-national'],
  },
  'keegan-bradley': {
    name: 'Keegan Bradley',
    slug: 'keegan-bradley',
    country: 'USA',
    age: 39,
    worldRanking: 21,
    avgDfsPoints: 63.8,
    winRate: 3.8,
    cutRate: 82.5,
    strokesGained: { offTheTee: 0.45, approach: 0.55, aroundTheGreen: 0.18, putting: 0.25, total: 1.43 },
    recentResults: [
      { tournament: 'BMW Championship', finish: 'T3' },
      { tournament: 'THE PLAYERS Championship', finish: 'T13' },
      { tournament: 'WM Phoenix Open', finish: 'T8' },
      { tournament: 'Arnold Palmer Invitational', finish: 'T11' },
      { tournament: 'Travelers Championship', finish: '1st' },
    ],
    bio: 'Keegan Bradley experienced a career renaissance that few predicted, returning to elite form after years of inconsistency. The Vermont native, who won the 2011 PGA Championship as a rookie, had faded from the upper echelon of professional golf before a resurgence in the 2023-2024 season. Bradley\'s game is balanced and steady — he drives the ball well enough, approaches consistently, and putts with confidence. His selection as the 2025 U.S. Ryder Cup captain underscores his respected standing in the game. In DFS, Bradley offers solid floor production without overwhelming ceiling, making him a dependable mid-tier option who rarely craters.',
    dfsStrategyTips: [
      'Bradley is a steady mid-tier play who offers reliable floor production without significant ceiling.',
      'His balanced profile makes him playable at most courses, though he doesn\'t have standout weeks at any specific venue type.',
      'Bradley is better suited for cash games than GPPs due to his moderate ceiling and consistent scoring.',
      'Look for value when Bradley is priced below $8,000 on DraftKings — that\'s where his floor provides the best return.',
    ],
    bestCourseFits: ['tpc-sawgrass', 'bay-hill', 'tpc-scottsdale'],
    worstCourseFits: ['torrey-pines-south', 'valhalla'],
  },
  'brian-harman': {
    name: 'Brian Harman',
    slug: 'brian-harman',
    country: 'USA',
    age: 37,
    worldRanking: 22,
    avgDfsPoints: 63.2,
    winRate: 3.5,
    cutRate: 85.8,
    strokesGained: { offTheTee: -0.15, approach: 0.48, aroundTheGreen: 0.52, putting: 0.55, total: 1.40 },
    recentResults: [
      { tournament: 'The Open Championship', finish: '1st' },
      { tournament: 'Sony Open', finish: 'T4' },
      { tournament: 'RBC Heritage', finish: 'T6' },
      { tournament: 'THE PLAYERS Championship', finish: 'T30' },
      { tournament: 'Arnold Palmer Invitational', finish: 'T19' },
    ],
    bio: 'Brian Harman shocked the golf world with a wire-to-wire victory at the 2023 Open Championship at Royal Liverpool, proving that elite short game and putting can still triumph over raw power in modern professional golf. The left-handed Georgian is one of the shortest hitters among top PGA Tour professionals, but he compensates with exceptional touch around the greens and one of the best putting strokes in the game. Harman\'s short game artistry allows him to scramble effectively and convert birdie putts that longer hitters leave themselves after less precise approaches. His Open Championship victory was a masterclass in scoring without distance. In DFS, Harman is a niche play who excels at specific course types where his short game dominance compensates for his lack of length.',
    dfsStrategyTips: [
      'Harman is the ultimate short-game specialist in DFS. His elite putting and scrambling make him a premium play at the right courses.',
      'Target him at Pebble Beach, Pinehurst No. 2, and TPC Scottsdale where short game and putting are critical.',
      'Avoid him at bomber courses like Torrey Pines South, Valhalla, and Augusta National where his lack of distance is a fatal flaw.',
      'Harman is frequently underowned, making him an excellent low-ownership GPP dart throw at his preferred venues.',
    ],
    bestCourseFits: ['pinehurst-no2', 'pebble-beach', 'tpc-scottsdale'],
    worstCourseFits: ['torrey-pines-south', 'valhalla', 'augusta-national'],
  },
  'jordan-spieth': {
    name: 'Jordan Spieth',
    slug: 'jordan-spieth',
    country: 'USA',
    age: 31,
    worldRanking: 25,
    avgDfsPoints: 62.5,
    winRate: 7.0,
    cutRate: 79.0,
    strokesGained: { offTheTee: -0.08, approach: 0.52, aroundTheGreen: 0.42, putting: 0.45, total: 1.31 },
    recentResults: [
      { tournament: 'Valero Texas Open', finish: '1st' },
      { tournament: 'THE PLAYERS Championship', finish: 'T28' },
      { tournament: 'Masters Tournament', finish: 'T22' },
      { tournament: 'RBC Heritage', finish: 'T14' },
      { tournament: 'Arnold Palmer Invitational', finish: 'T35' },
    ],
    bio: 'Jordan Spieth is a three-time major champion and one of the most gifted short game players in the history of professional golf. The Dallas native burst onto the scene as a teenager, winning the Masters and U.S. Open in 2015 at age 21, before adding The Open Championship in 2017. Spieth\'s game has always been defined by magical short game touch and elite putting — he sees lines and reads greens with an intuition that few players possess. However, his ball-striking, particularly off the tee, has been inconsistent in recent years, leading to stretches of poor form that have dropped him in the world rankings. When Spieth\'s tee-to-green game cooperates with his otherworldly short game, the results can be spectacular. When it doesn\'t, the missed cuts pile up.',
    dfsStrategyTips: [
      'Spieth is one of the highest-variance plays in DFS. He can win any tournament or miss the cut — there is rarely an in-between.',
      'His elite putting and short game make him a premium play at Pebble Beach, Pinehurst No. 2, and similar touch-oriented courses.',
      'Spieth is almost exclusively a GPP play given his 79% cut rate. Avoid him in cash games.',
      'When Spieth\'s price drops below $7,500 on DraftKings after a string of poor results, he becomes a high-ceiling GPP dart throw.',
    ],
    bestCourseFits: ['pebble-beach', 'pinehurst-no2', 'tpc-scottsdale'],
    worstCourseFits: ['torrey-pines-south', 'valhalla'],
  },
  'will-zalatoris': {
    name: 'Will Zalatoris',
    slug: 'will-zalatoris',
    country: 'USA',
    age: 28,
    worldRanking: 23,
    avgDfsPoints: 64.5,
    winRate: 3.0,
    cutRate: 81.5,
    strokesGained: { offTheTee: 0.42, approach: 1.18, aroundTheGreen: -0.20, putting: -0.25, total: 1.15 },
    recentResults: [
      { tournament: 'Arnold Palmer Invitational', finish: 'T5' },
      { tournament: 'THE PLAYERS Championship', finish: 'T10' },
      { tournament: 'Masters Tournament', finish: 'T6' },
      { tournament: 'PGA Championship', finish: 'T4' },
      { tournament: 'Memorial Tournament', finish: 'T12' },
    ],
    bio: 'Will Zalatoris is one of the purest ball-strikers on the PGA Tour, with iron play that ranks among the very best in the world. The San Francisco native turned professional in 2018 and quickly made his mark with a series of remarkable major championship performances — finishing runner-up at the 2021 Masters as a non-member and later claiming a dramatic victory at the 2022 FedEx St. Jude Championship. Zalatoris\'s approach play is his calling card, as he consistently hits greens in regulation and attacks pins with precision that few can match. The challenge for Zalatoris has been his putting, which can range from below average to actively detrimental. When combined with occasional short game struggles, his putting inconsistency creates a wide range of possible outcomes in any given tournament.',
    dfsStrategyTips: [
      'Zalatoris is the most extreme ball-striker-dependent play in DFS. His iron play is top-3 on tour, but his putting can tank his results.',
      'Target him at Augusta National, TPC Sawgrass, and other courses where approach play is the dominant success factor.',
      'His major championship track record is exceptional — he consistently contends at the game\'s biggest events.',
      'Zalatoris is a pure GPP play. His putting variance creates too much floor risk for cash games.',
    ],
    bestCourseFits: ['augusta-national', 'tpc-sawgrass', 'bay-hill'],
    worstCourseFits: ['tpc-scottsdale', 'pinehurst-no2'],
  },
  'russell-henley': {
    name: 'Russell Henley',
    slug: 'russell-henley',
    country: 'USA',
    age: 35,
    worldRanking: 24,
    avgDfsPoints: 65.0,
    winRate: 3.2,
    cutRate: 87.8,
    strokesGained: { offTheTee: 0.28, approach: 0.72, aroundTheGreen: 0.18, putting: 0.30, total: 1.48 },
    recentResults: [
      { tournament: 'World Wide Technology Championship', finish: '1st' },
      { tournament: 'THE PLAYERS Championship', finish: 'T8' },
      { tournament: 'Arnold Palmer Invitational', finish: 'T6' },
      { tournament: 'RBC Heritage', finish: 'T3' },
      { tournament: 'Charles Schwab Challenge', finish: 'T5' },
    ],
    bio: 'Russell Henley is one of the most underrated players on the PGA Tour, quietly posting consistent results year after year without the fanfare that accompanies higher-profile competitors. The University of Georgia product has won multiple PGA Tour events and maintains one of the highest cut rates on tour, making him a model of reliability. Henley\'s game is balanced and efficient — he drives the ball adequately, approaches consistently, chips cleanly, and putts solidly. He doesn\'t have an elite weapon that jumps off the page, but the absence of any significant weakness means he grinds out strong finishes week after week. In DFS, Henley is a hidden gem who offers excellent floor production at a price point that allows roster construction flexibility.',
    dfsStrategyTips: [
      'Henley is one of the best-kept secrets in golf DFS. His 87%+ cut rate and consistent scoring provide an elite floor.',
      'He\'s typically priced $1,000-$2,000 below where his production suggests he should be, creating persistent value.',
      'Henley\'s balanced profile makes him a solid play at most courses on the schedule — he has few bad course fits.',
      'In cash games, Henley is one of the safest mid-tier options available. In GPPs, use him to free up salary for higher-ceiling plays.',
    ],
    bestCourseFits: ['tpc-sawgrass', 'bay-hill', 'tpc-scottsdale'],
    worstCourseFits: ['torrey-pines-south'],
  },
  'tom-kim': {
    name: 'Tom Kim',
    slug: 'tom-kim',
    country: 'South Korea',
    age: 22,
    worldRanking: 26,
    avgDfsPoints: 66.8,
    winRate: 4.0,
    cutRate: 83.5,
    strokesGained: { offTheTee: 0.35, approach: 0.65, aroundTheGreen: 0.30, putting: 0.42, total: 1.72 },
    recentResults: [
      { tournament: 'Shriners Children\'s Open', finish: '1st' },
      { tournament: 'Wyndham Championship', finish: '1st' },
      { tournament: 'THE PLAYERS Championship', finish: 'T19' },
      { tournament: 'Arnold Palmer Invitational', finish: 'T15' },
      { tournament: 'WM Phoenix Open', finish: 'T7' },
    ],
    bio: 'Tom Kim is one of the brightest young stars in professional golf, having already won three PGA Tour events before his 22nd birthday. The South Korean sensation combines a charismatic personality with a surprisingly complete game for his age. Kim\'s strengths lie in his putting, short game touch, and ability to score in bunches — he\'s capable of rattling off three or four birdies in a row when his confidence is flowing. His ball-striking continues to develop, and his driving distance has improved as his body matures. Kim\'s popularity and marketability have made him one of the tour\'s most recognizable faces, but it\'s his on-course performance that truly sets him apart. He plays with a joy and fearlessness that makes him capable of winning any week.',
    dfsStrategyTips: [
      'Kim is a young, aggressive player who creates birdie streaks. He\'s an excellent DraftKings play where streak bonuses add value.',
      'His putting and short game make him a strong fit at TPC Scottsdale, Pebble Beach, and other touch-oriented courses.',
      'Kim\'s ownership has been climbing, but he still offers leverage in weeks where bigger names dominate the ownership conversation.',
      'Target him in GPPs when he\'s coming off a good recent result — his confidence-based playing style means form matters more than usual.',
    ],
    bestCourseFits: ['tpc-scottsdale', 'pebble-beach', 'bay-hill'],
    worstCourseFits: ['torrey-pines-south', 'valhalla'],
  },
  'rickie-fowler': {
    name: 'Rickie Fowler',
    slug: 'rickie-fowler',
    country: 'USA',
    age: 36,
    worldRanking: 35,
    avgDfsPoints: 58.5,
    winRate: 3.5,
    cutRate: 76.0,
    strokesGained: { offTheTee: 0.32, approach: 0.35, aroundTheGreen: 0.18, putting: 0.25, total: 1.10 },
    recentResults: [
      { tournament: 'Rocket Mortgage Classic', finish: '1st' },
      { tournament: 'THE PLAYERS Championship', finish: 'T32' },
      { tournament: 'Arnold Palmer Invitational', finish: 'T25' },
      { tournament: 'WM Phoenix Open', finish: 'T18' },
      { tournament: 'U.S. Open', finish: 'T3' },
    ],
    bio: 'Rickie Fowler is one of the most popular and recognizable figures in professional golf, known for his colorful attire and engaging personality. The Oklahoma State product has been a PGA Tour fixture since 2010, with multiple victories and a devoted fan following that few players can match. Fowler\'s game is well-rounded without any elite weapon — he drives the ball adequately, approaches consistently, and putts well enough to compete most weeks. His career resurgence in 2023, highlighted by a victory at the Rocket Mortgage Classic and a near-miss at the U.S. Open, reminded the golf world of his talent. In DFS, Fowler profiles as a mid-to-low tier option whose popularity can inflate his ownership, making him a better fade than play in many weeks.',
    dfsStrategyTips: [
      'Fowler\'s DFS value is often limited by inflated ownership driven by his popularity rather than his performance.',
      'His best DFS weeks tend to come at courses he knows well. Strong course history is a key indicator for Fowler plays.',
      'His 76% cut rate makes him a risky cash game option. He\'s better suited as an occasional GPP dart throw when underpriced.',
      'Fade Fowler in majors where his ownership will be disproportionately high relative to his probability of contending.',
    ],
    bestCourseFits: ['tpc-scottsdale', 'bay-hill', 'tpc-sawgrass'],
    worstCourseFits: ['torrey-pines-south', 'valhalla', 'augusta-national'],
  },
  'cameron-smith': {
    name: 'Cameron Smith',
    slug: 'cameron-smith',
    country: 'Australia',
    age: 31,
    worldRanking: 28,
    avgDfsPoints: 61.0,
    winRate: 5.2,
    cutRate: 80.0,
    strokesGained: { offTheTee: 0.10, approach: 0.45, aroundTheGreen: 0.60, putting: 0.65, total: 1.80 },
    recentResults: [
      { tournament: 'The Open Championship', finish: 'T8' },
      { tournament: 'Masters Tournament', finish: 'T12' },
      { tournament: 'LIV Golf Houston', finish: '1st' },
      { tournament: 'PGA Championship', finish: 'T20' },
      { tournament: 'U.S. Open', finish: 'T15' },
    ],
    bio: 'Cameron Smith is one of the most gifted short game players and putters in professional golf, possessing a touch and feel around the greens that is virtually unmatched. The Australian won The Open Championship in 2022 with a final-round 64 that demonstrated his ability to score in the most pressure-packed situations. Smith\'s game is built on elite putting and scrambling — he leads the tour in strokes gained putting when he plays PGA Tour events and has an uncanny ability to get up and down from seemingly impossible positions. His move to LIV Golf has limited his PGA Tour appearances to major championships, but he remains a serious contender at every major he enters. Smith\'s short game wizardry makes him a unique DFS asset — few players can generate the same scoring from 100 yards and in.',
    dfsStrategyTips: [
      'Smith is a major-championship specialist in DFS. Target him at The Open and Masters where his short game is maximally valuable.',
      'His elite putting makes him dangerous at courses with large, undulating greens where putting variance is amplified.',
      'Smith\'s limited PGA Tour schedule means he can be underowned in majors, creating excellent GPP leverage.',
      'He excels at Pinehurst No. 2, Pebble Beach, and other courses where short game artistry separates the contenders.',
    ],
    bestCourseFits: ['pinehurst-no2', 'pebble-beach', 'tpc-scottsdale'],
    worstCourseFits: ['torrey-pines-south', 'valhalla'],
  },
  'dustin-johnson': {
    name: 'Dustin Johnson',
    slug: 'dustin-johnson',
    country: 'USA',
    age: 41,
    worldRanking: 45,
    avgDfsPoints: 55.5,
    winRate: 8.2,
    cutRate: 74.0,
    strokesGained: { offTheTee: 0.95, approach: 0.55, aroundTheGreen: 0.10, putting: -0.05, total: 1.55 },
    recentResults: [
      { tournament: 'Masters Tournament', finish: 'T18' },
      { tournament: 'PGA Championship', finish: 'T25' },
      { tournament: 'LIV Golf Las Vegas', finish: '1st' },
      { tournament: 'The Open Championship', finish: 'T30' },
      { tournament: 'U.S. Open', finish: 'T28' },
    ],
    bio: 'Dustin Johnson is a two-time major champion and former world number one who was arguably the most naturally gifted golfer of his generation. The South Carolina native\'s combination of elite length off the tee, athletic ability, and effortless power made him one of the most dominant players on the PGA Tour for over a decade. Johnson won the 2016 U.S. Open and the 2020 Masters with a record-setting 20-under performance at Augusta National. His move to LIV Golf in 2022 has limited his major championship appearances, and age has begun to erode his dominance. However, Johnson still possesses the raw talent to compete at the highest level on weeks when his interest and motivation align. In DFS, Johnson is now a high-risk, moderate-reward option best deployed selectively in major championship GPPs.',
    dfsStrategyTips: [
      'Johnson is past his prime but still dangerous at courses where driving distance is king. Augusta and Torrey Pines remain good fits.',
      'His 74% cut rate makes him a high-risk DFS play. Only deploy him in GPPs where a missed cut won\'t sink your portfolio.',
      'Johnson\'s ownership in majors has decreased as his form has declined, creating occasional leverage opportunities.',
      'Treat Johnson as a nostalgia fade in most weeks — his name recognition inflates ownership beyond what his current form justifies.',
    ],
    bestCourseFits: ['augusta-national', 'torrey-pines-south', 'valhalla'],
    worstCourseFits: ['pebble-beach', 'pinehurst-no2'],
  },
  'sam-burns': {
    name: 'Sam Burns',
    slug: 'sam-burns',
    country: 'USA',
    age: 28,
    worldRanking: 27,
    avgDfsPoints: 64.0,
    winRate: 4.5,
    cutRate: 82.0,
    strokesGained: { offTheTee: 0.55, approach: 0.58, aroundTheGreen: 0.15, putting: 0.42, total: 1.70 },
    recentResults: [
      { tournament: 'Charles Schwab Challenge', finish: '1st' },
      { tournament: 'Valspar Championship', finish: '1st' },
      { tournament: 'THE PLAYERS Championship', finish: 'T21' },
      { tournament: 'Arnold Palmer Invitational', finish: 'T16' },
      { tournament: 'Masters Tournament', finish: 'T20' },
    ],
    bio: 'Sam Burns has steadily built one of the most impressive resumes among the PGA Tour\'s under-30 generation, with multiple victories demonstrating his ability to close out tournaments. The LSU product from Shreveport, Louisiana combines solid ball-striking with excellent putting, a combination that has produced four PGA Tour victories and counting. Burns\'s game is well-suited to a variety of course types, though he tends to perform best at venues where putting is a significant differentiator. His comfort on bermuda grass greens, a product of growing up in Louisiana, gives him an edge at Southern venues. Burns\'s consistency and ceiling potential make him a strong all-around DFS option who can anchor both cash game and GPP lineups.',
    dfsStrategyTips: [
      'Burns excels on bermuda grass putting surfaces. Target him at TPC Sawgrass, Bay Hill, and other bermuda-green venues.',
      'His putting prowess creates consistent scoring, making him a solid cash game option in the mid-tier salary range.',
      'Burns tends to play well in bunches — when he\'s in form, ride the hot streak in DFS.',
      'His ownership is typically moderate (8-14%), offering decent GPP leverage without being truly contrarian.',
    ],
    bestCourseFits: ['tpc-sawgrass', 'bay-hill', 'tpc-scottsdale'],
    worstCourseFits: ['pebble-beach', 'torrey-pines-south'],
  },
  'robert-macintyre': {
    name: 'Robert MacIntyre',
    slug: 'robert-macintyre',
    country: 'Scotland',
    age: 28,
    worldRanking: 30,
    avgDfsPoints: 62.5,
    winRate: 3.0,
    cutRate: 83.0,
    strokesGained: { offTheTee: 0.58, approach: 0.52, aroundTheGreen: 0.28, putting: 0.15, total: 1.53 },
    recentResults: [
      { tournament: 'RBC Canadian Open', finish: '1st' },
      { tournament: 'Scottish Open', finish: '1st' },
      { tournament: 'THE PLAYERS Championship', finish: 'T12' },
      { tournament: 'Arnold Palmer Invitational', finish: 'T10' },
      { tournament: 'The Open Championship', finish: 'T8' },
    ],
    bio: 'Robert MacIntyre has emerged as one of Scotland\'s brightest golfing talents, combining left-handed flair with a tenacious competitive spirit that has produced multiple victories on both the PGA and European Tours. The Oban native\'s game is well-rounded with particular strengths off the tee and around the green, giving him a versatile profile that travels well across different course types. MacIntyre\'s emotional playing style energizes galleries and creates momentum-driven performances where he can string together birdies when the vibes are right. His 2024 breakthrough on the PGA Tour signaled that he is ready to compete at the highest level on a weekly basis. In DFS, MacIntyre profiles as a solid mid-tier option with enough ceiling to contend and enough floor to protect cash game lineups.',
    dfsStrategyTips: [
      'MacIntyre is a strong play at courses that reward driving and short game, particularly links-style venues.',
      'His left-handed shot shape can be advantageous at courses with dogleg-left holes, providing a unique course-fit angle.',
      'MacIntyre\'s ownership tends to be low to moderate on the PGA Tour, creating consistent GPP leverage.',
      'Target him at The Open Championship and other events where his experience in windy conditions provides an edge.',
    ],
    bestCourseFits: ['bay-hill', 'tpc-sawgrass', 'pinehurst-no2'],
    worstCourseFits: ['tpc-scottsdale', 'torrey-pines-south'],
  },
  'aaron-rai': {
    name: 'Aaron Rai',
    slug: 'aaron-rai',
    country: 'England',
    age: 29,
    worldRanking: 32,
    avgDfsPoints: 61.8,
    winRate: 2.5,
    cutRate: 84.0,
    strokesGained: { offTheTee: 0.18, approach: 0.82, aroundTheGreen: 0.25, putting: 0.20, total: 1.45 },
    recentResults: [
      { tournament: 'Wyndham Championship', finish: '1st' },
      { tournament: 'THE PLAYERS Championship', finish: 'T14' },
      { tournament: 'Arnold Palmer Invitational', finish: 'T7' },
      { tournament: 'Farmers Insurance Open', finish: 'T5' },
      { tournament: 'RBC Heritage', finish: 'T9' },
    ],
    bio: 'Aaron Rai has quietly become one of the most consistent players on the PGA Tour, posting steady results that belie his relatively low public profile. The English golfer from Wolverhampton combines precise iron play with solid short game touch, creating a scoring profile that plays well at a variety of courses. Rai\'s approach play is the strongest facet of his game, and he consistently finds greens in regulation at a rate that keeps him in contention most weeks. His driving distance is below tour average, but his accuracy and course management compensate effectively. Rai represents the type of under-the-radar DFS asset that sharp players seek out — a consistent performer with a low ownership profile and a price tag that provides lineup construction flexibility.',
    dfsStrategyTips: [
      'Rai is a textbook low-ownership value play in DFS. He\'s consistently underpriced relative to his production.',
      'His approach play strength makes him a natural fit at TPC Sawgrass, Pebble Beach, and other precision-demanding courses.',
      'Rai\'s 84% cut rate and consistent scoring make him a solid cash game option in the low-to-mid salary tier.',
      'In GPPs, Rai is an excellent salary saver who frees up cap space for higher-ceiling plays at the top of the salary range.',
    ],
    bestCourseFits: ['tpc-sawgrass', 'pebble-beach', 'bay-hill'],
    worstCourseFits: ['torrey-pines-south', 'valhalla'],
  },
  'billy-horschel': {
    name: 'Billy Horschel',
    slug: 'billy-horschel',
    country: 'USA',
    age: 38,
    worldRanking: 34,
    avgDfsPoints: 60.5,
    winRate: 3.8,
    cutRate: 83.5,
    strokesGained: { offTheTee: 0.25, approach: 0.55, aroundTheGreen: 0.32, putting: 0.28, total: 1.40 },
    recentResults: [
      { tournament: 'Memorial Tournament', finish: 'T4' },
      { tournament: 'THE PLAYERS Championship', finish: 'T16' },
      { tournament: 'Arnold Palmer Invitational', finish: 'T8' },
      { tournament: 'RBC Heritage', finish: 'T12' },
      { tournament: 'Charles Schwab Challenge', finish: 'T6' },
    ],
    bio: 'Billy Horschel is a seven-time PGA Tour winner known for his emotional intensity and unwavering competitive fire. The University of Florida product has been a consistent presence on tour since 2010, with his most notable achievement being a dominant FedExCup playoff performance in 2014 that included back-to-back victories. Horschel\'s game is built on solid fundamentals across all categories — he drives the ball accurately, approaches well, has reliable short game touch, and putts consistently. His emotional nature can be both an asset (when channeled positively into momentum-building birdies) and a liability (when frustration leads to compound errors). In DFS, Horschel is a reliable mid-to-low tier option who offers steady floor production and occasional upside.',
    dfsStrategyTips: [
      'Horschel is a course-history play. He has specific venues where he consistently performs well — check his track record before rostering.',
      'His balanced profile makes him a safe cash game option in the lower salary tiers when you need floor protection.',
      'Horschel\'s ownership is typically very low (3-8%), making him an excellent GPP salary saver with legitimate upside.',
      'He tends to perform well at Bay Hill, TPC Sawgrass, and other Florida courses where he has extensive experience.',
    ],
    bestCourseFits: ['bay-hill', 'tpc-sawgrass', 'tpc-scottsdale'],
    worstCourseFits: ['torrey-pines-south', 'valhalla', 'augusta-national'],
  },
};

/** Get all golfer profiles as an array, sorted by world ranking */
export function getAllGolfers(): GolferProfile[] {
  return Object.values(GOLFER_PROFILES).sort((a, b) => a.worldRanking - b.worldRanking);
}

/** Get a single golfer profile by slug */
export function getGolferBySlug(slug: string): GolferProfile | undefined {
  return GOLFER_PROFILES[slug];
}
